;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright (c) 2013 The Khronos Group Inc.
;;;
;;; Permission is hereby granted, free of charge, to any person obtaining a
;;; copy of this software and/or associated documentation files (the
;;; "Materials"), to deal in the Materials without restriction, including
;;; without limitation the rights to use, copy, modify, merge, publish,
;;; distribute, sublicense, and/or sell copies of the Materials, and to
;;; permit persons to whom the Materials are furnished to do so, subject to
;;; the following conditions:
;;;
;;; The above copyright notice and this permission notice shall be included
;;; in all copies or substantial portions of the Materials.
;;;
;;; THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
;;; IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
;;; CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
;;; TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
;;; MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
;;;
;;; ------------------------------------------------------------------------

(in-package #:cl-opengl-bindings)

;;; generated 2013-07-30T19:14:12Z
;;; from gl.xml @ svn rev 22553, 2013-07-29T23:02:42.773972Z

(defglfun ("glClipPlanef" clip-plane-f) :void
  (p enum)
  (eqn (:pointer float)))

(defglfun ("glFrustumf" frustum-f) :void
  (l float)
  (r float)
  (b float)
  (tee float)
  (n float)
  (f float))

(defglfun ("glGetClipPlanef" get-clip-plane-f) :void
  (plane enum)
  (equation (:pointer float)))

(defglfun ("glOrthof" ortho-f) :void
  (l float)
  (r float)
  (b float)
  (tee float)
  (n float)
  (f float))

(defglfun ("glAlphaFuncx" alpha-func-x) :void
  (func enum)
  (ref fixed))

(defglfun ("glClearColorx" clear-color-x) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglfun ("glClearDepthx" clear-depth-x) :void
  (depth fixed))

(defglfun ("glClipPlanex" clip-plane-x) :void
  (plane enum)
  (equation (:pointer fixed)))

(defglfun ("glColor4x" color-4x) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglfun ("glDepthRangex" depth-range-x) :void
  (n fixed)
  (f fixed))

(defglfun ("glFogx" fog-x) :void
  (pname enum)
  (param fixed))

(defglfun ("glFogxv" fog-xv) :void
  (pname enum)
  (param (:pointer fixed)))

(defglfun ("glFrustumx" frustum-x) :void
  (l fixed)
  (r fixed)
  (b fixed)
  (tee fixed)
  (n fixed)
  (f fixed))

(defglfun ("glGetClipPlanex" get-clip-plane-x) :void
  (plane enum)
  (equation (:pointer fixed)))

(defglfun ("glGetFixedv" get-fixed-v) :void
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glGetLightxv" get-light-xv) :void
  (light enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glGetMaterialxv" get-material-xv) :void
  (face enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glGetTexEnvxv" get-tex-env-xv) :void
  (target enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glGetTexParameterxv" get-tex-parameter-xv) :void
  (target enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glLightModelx" light-model-x) :void
  (pname enum)
  (param fixed))

(defglfun ("glLightModelxv" light-model-xv) :void
  (pname enum)
  (param (:pointer fixed)))

(defglfun ("glLightx" light-x) :void
  (light enum)
  (pname enum)
  (param fixed))

(defglfun ("glLightxv" light-xv) :void
  (light enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glLineWidthx" line-width-x) :void
  (width fixed))

(defglfun ("glLoadMatrixx" load-matrix-x) :void
  (m (:pointer fixed)))

(defglfun ("glMaterialx" material-x) :void
  (face enum)
  (pname enum)
  (param fixed))

(defglfun ("glMaterialxv" material-xv) :void
  (face enum)
  (pname enum)
  (param (:pointer fixed)))

(defglfun ("glMultMatrixx" mult-matrix-x) :void
  (m (:pointer fixed)))

(defglfun ("glMultiTexCoord4x" multi-tex-coord-4x) :void
  (texture enum)
  (s fixed)
  (tee fixed)
  (r fixed)
  (q fixed))

(defglfun ("glNormal3x" normal-3x) :void
  (nx fixed)
  (ny fixed)
  (nz fixed))

(defglfun ("glOrthox" ortho-x) :void
  (l fixed)
  (r fixed)
  (b fixed)
  (tee fixed)
  (n fixed)
  (f fixed))

(defglfun ("glPointParameterx" point-parameter-x) :void
  (pname enum)
  (param fixed))

(defglfun ("glPointParameterxv" point-parameter-xv) :void
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glPointSizex" point-size-x) :void
  (size fixed))

(defglfun ("glPolygonOffsetx" polygon-offset-x) :void
  (factor fixed)
  (units fixed))

(defglfun ("glRotatex" rotate-x) :void
  (angle fixed)
  (x fixed)
  (y fixed)
  (z fixed))

(defglfun ("glSampleCoveragex" sample-coverage-x) :void
  (value clampx)
  (invert boolean))

(defglfun ("glScalex" scale-x) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglfun ("glTexEnvx" tex-env-x) :void
  (target enum)
  (pname enum)
  (param fixed))

(defglfun ("glTexEnvxv" tex-env-xv) :void
  (target enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glTexParameterx" tex-parameter-x) :void
  (target enum)
  (pname enum)
  (param fixed))

(defglfun ("glTexParameterxv" tex-parameter-xv) :void
  (target enum)
  (pname enum)
  (params (:pointer fixed)))

(defglfun ("glTranslatex" translate-x) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glClipPlanefIMG" clip-plane-f-img) :void
  (p enum)
  (eqn (:pointer float)))

(defglextfun ("glClipPlanexIMG" clip-plane-x-img) :void
  (p enum)
  (eqn (:pointer fixed)))

(defglextfun ("glBlendEquationSeparateOES" blend-equation-separate-oes) :void
  (modeRGB enum)
  (modeAlpha enum))

(defglextfun ("glBlendFuncSeparateOES" blend-func-separate-oes) :void
  (srcRGB enum)
  (dstRGB enum)
  (srcAlpha enum)
  (dstAlpha enum))

(defglextfun ("glBlendEquationOES" blend-equation-oes) :void
  (mode enum))

(defglextfun ("glDrawTexsOES" draw-tex-s-oes) :void
  (x short)
  (y short)
  (z short)
  (width short)
  (height short))

(defglextfun ("glDrawTexiOES" draw-tex-i-oes) :void
  (x int)
  (y int)
  (z int)
  (width int)
  (height int))

(defglextfun ("glDrawTexxOES" draw-tex-x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed)
  (width fixed)
  (height fixed))

(defglextfun ("glDrawTexsvOES" draw-tex-sv-oes) :void
  (coords (:pointer short)))

(defglextfun ("glDrawTexivOES" draw-tex-iv-oes) :void
  (coords (:pointer int)))

(defglextfun ("glDrawTexxvOES" draw-tex-xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glDrawTexfOES" draw-tex-f-oes) :void
  (x float)
  (y float)
  (z float)
  (width float)
  (height float))

(defglextfun ("glDrawTexfvOES" draw-tex-fv-oes) :void
  (coords (:pointer float)))

(defglextfun ("glIsRenderbufferOES" is-renderbuffer-oes) boolean
  (renderbuffer uint))

(defglextfun ("glBindRenderbufferOES" bind-renderbuffer-oes) :void
  (target enum)
  (renderbuffer uint))

(defglextfun ("glDeleteRenderbuffersOES" delete-renderbuffers-oes) :void
  (n sizei)
  (renderbuffers (:pointer uint)))

(defglextfun ("glGenRenderbuffersOES" gen-renderbuffers-oes) :void
  (n sizei)
  (renderbuffers (:pointer uint)))

(defglextfun ("glRenderbufferStorageOES" renderbuffer-storage-oes) :void
  (target enum)
  (internalformat enum)
  (width sizei)
  (height sizei))

(defglextfun ("glGetRenderbufferParameterivOES" get-renderbuffer-parameter-iv-oes) :void
  (target enum)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glIsFramebufferOES" is-framebuffer-oes) boolean
  (framebuffer uint))

(defglextfun ("glBindFramebufferOES" bind-framebuffer-oes) :void
  (target enum)
  (framebuffer uint))

(defglextfun ("glDeleteFramebuffersOES" delete-framebuffers-oes) :void
  (n sizei)
  (framebuffers (:pointer uint)))

(defglextfun ("glGenFramebuffersOES" gen-framebuffers-oes) :void
  (n sizei)
  (framebuffers (:pointer uint)))

(defglextfun ("glCheckFramebufferStatusOES" check-framebuffer-status-oes) enum
  (target enum))

(defglextfun ("glFramebufferRenderbufferOES" framebuffer-renderbuffer-oes) :void
  (target enum)
  (attachment enum)
  (renderbuffertarget enum)
  (renderbuffer uint))

(defglextfun ("glFramebufferTexture2DOES" framebuffer-texture-2d-oes) :void
  (target enum)
  (attachment enum)
  (textarget enum)
  (texture uint)
  (level int))

(defglextfun ("glGetFramebufferAttachmentParameterivOES" get-framebuffer-attachment-parameter-iv-oes) :void
  (target enum)
  (attachment enum)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glGenerateMipmapOES" generate-mipmap-oes) :void
  (target enum))

(defglextfun ("glCurrentPaletteMatrixOES" current-palette-matrix-oes) :void
  (matrixpaletteindex uint))

(defglextfun ("glLoadPaletteFromModelViewMatrixOES" load-palette-from-model-view-matrix-oes) :void)

(defglextfun ("glMatrixIndexPointerOES" matrix-index-pointer-oes) :void
  (size int)
  (type enum)
  (stride sizei)
  (pointer (:pointer void)))

(defglextfun ("glWeightPointerOES" weight-pointer-oes) :void
  (size int)
  (type enum)
  (stride sizei)
  (pointer (:pointer void)))

(defglextfun ("glPointSizePointerOES" point-size-pointer-oes) :void
  (type enum)
  (stride sizei)
  (pointer (:pointer :void)))

(defglextfun ("glTexGenfOES" tex-gen-f-oes) :void
  (coord enum)
  (pname enum)
  (param float))

(defglextfun ("glTexGenfvOES" tex-gen-fv-oes) :void
  (coord enum)
  (pname enum)
  (params (:pointer float)))

(defglextfun ("glTexGeniOES" tex-gen-i-oes) :void
  (coord enum)
  (pname enum)
  (param int))

(defglextfun ("glTexGenivOES" tex-gen-iv-oes) :void
  (coord enum)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glGetTexGenfvOES" get-tex-gen-fv-oes) :void
  (coord enum)
  (pname enum)
  (params (:pointer float)))

(defglextfun ("glGetTexGenivOES" get-tex-gen-iv-oes) :void
  (coord enum)
  (pname enum)
  (params (:pointer int)))

