;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2020-10-03T16:20:47Z
;;; from gl.xml @ git sha 9274192362a0ac6912fd27b0c8ff0559fc658e21, 2020-09-29T11:45:14Z

(defglfun ("glPointSize" point-size) :void
  (size float))

(defglfun ("glLogicOp" logic-op) :void
  (opcode logic-op))

(defglfun ("glColor4f" color-4f) :void
  (red float)
  (green float)
  (blue float)
  (alpha float))

(defglfun ("glColor4ub" color-4ub) :void
  (red ubyte)
  (green ubyte)
  (blue ubyte)
  (alpha ubyte))

(defglfun ("glNormal3f" normal-3f) :void
  (nx float)
  (ny float)
  (nz float))

(defglfun ("glFogf" fog-f) :void
  (pname fog-parameter)
  (param float))

(defglfun ("glFogfv" fog-fv) :void
  (pname fog-parameter)
  (params (:pointer float)))

(defglfun ("glLightf" light-f) :void
  (light light-name)
  (pname light-parameter)
  (param float))

(defglfun ("glLightfv" light-fv) :void
  (light light-name)
  (pname light-parameter)
  (params (:pointer float)))

(defglfun ("glLightModelf" light-model-f) :void
  (pname light-model-parameter)
  (param float))

(defglfun ("glLightModelfv" light-model-fv) :void
  (pname light-model-parameter)
  (params (:pointer float)))

(defglfun ("glMaterialf" material-f) :void
  (face material-face)
  (pname material-parameter)
  (param float))

(defglfun ("glMaterialfv" material-fv) :void
  (face material-face)
  (pname material-parameter)
  (params (:pointer float)))

(defglfun ("glShadeModel" shade-model) :void
  (mode shading-model))

(defglfun ("glTexEnvf" tex-env-f) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (param float))

(defglfun ("glTexEnvfv" tex-env-fv) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer float)))

(defglfun ("glTexEnvi" tex-env-i) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (param int))

(defglfun ("glTexEnviv" tex-env-iv) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer int)))

(defglfun ("glAlphaFunc" alpha-func) :void
  (func alpha-function)
  (ref float))

(defglfun ("glGetLightfv" get-light-fv) :void
  (light light-name)
  (pname light-parameter)
  (params (:pointer float)))

(defglfun ("glGetMaterialfv" get-material-fv) :void
  (face material-face)
  (pname material-parameter)
  (params (:pointer float)))

(defglfun ("glGetTexEnvfv" get-tex-env-fv) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer float)))

(defglfun ("glGetTexEnviv" get-tex-env-iv) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer int)))

(defglfun ("glLoadIdentity" load-identity) :void)

(defglfun ("glLoadMatrixf" load-matrix-f) :void
  (m (:pointer float)))

(defglfun ("glMatrixMode" matrix-mode) :void
  (mode matrix-mode))

(defglfun ("glMultMatrixf" mult-matrix-f) :void
  (m (:pointer float)))

(defglfun ("glPopMatrix" pop-matrix) :void)

(defglfun ("glPushMatrix" push-matrix) :void)

(defglfun ("glRotatef" rotate-f) :void
  (angle float)
  (x float)
  (y float)
  (z float))

(defglfun ("glScalef" scale-f) :void
  (x float)
  (y float)
  (z float))

(defglfun ("glTranslatef" translate-f) :void
  (x float)
  (y float)
  (z float))

(defglfun ("glColorPointer" color-pointer) :void
  (size int)
  (type color-pointer-type)
  (stride sizei)
  (pointer offset-or-pointer))

(defglfun ("glDisableClientState" disable-client-state) :void
  (array enable-cap))

(defglfun ("glEnableClientState" enable-client-state) :void
  (array enable-cap))

(defglfun ("glNormalPointer" normal-pointer) :void
  (type normal-pointer-type)
  (stride sizei)
  (pointer offset-or-pointer))

(defglfun ("glTexCoordPointer" tex-coord-pointer) :void
  (size int)
  (type tex-coord-pointer-type)
  (stride sizei)
  (pointer offset-or-pointer))

(defglfun ("glVertexPointer" vertex-pointer) :void
  (size int)
  (type vertex-pointer-type)
  (stride sizei)
  (pointer offset-or-pointer))

(defglextfun ("glClientActiveTexture" client-active-texture) :void
  (texture texture-unit))

(defglextfun ("glMultiTexCoord4f" multi-tex-coord-4f) :void
  (target texture-unit)
  (s float)
  (tee float)
  (r float)
  (q float))

(defglextfun ("glPointParameterf" point-parameter-f) :void
  (pname point-parameter-name-arb)
  (param float))

(defglextfun ("glPointParameterfv" point-parameter-fv) :void
  (pname point-parameter-name-arb)
  (params (:pointer float)))

(defglextfun ("glMultiTexCoord1bOES" multi-tex-coord-1b-oes) :void
  (texture texture-unit)
  (s byte))

(defglextfun ("glMultiTexCoord1bvOES" multi-tex-coord-1bv-oes) :void
  (texture texture-unit)
  (coords (:pointer byte)))

(defglextfun ("glMultiTexCoord2bOES" multi-tex-coord-2b-oes) :void
  (texture texture-unit)
  (s byte)
  (tee byte))

(defglextfun ("glMultiTexCoord2bvOES" multi-tex-coord-2bv-oes) :void
  (texture texture-unit)
  (coords (:pointer byte)))

(defglextfun ("glMultiTexCoord3bOES" multi-tex-coord-3b-oes) :void
  (texture texture-unit)
  (s byte)
  (tee byte)
  (r byte))

(defglextfun ("glMultiTexCoord3bvOES" multi-tex-coord-3bv-oes) :void
  (texture texture-unit)
  (coords (:pointer byte)))

(defglextfun ("glMultiTexCoord4bOES" multi-tex-coord-4b-oes) :void
  (texture texture-unit)
  (s byte)
  (tee byte)
  (r byte)
  (q byte))

(defglextfun ("glMultiTexCoord4bvOES" multi-tex-coord-4bv-oes) :void
  (texture texture-unit)
  (coords (:pointer byte)))

(defglextfun ("glTexCoord1bOES" tex-coord-1b-oes) :void
  (s byte))

(defglextfun ("glTexCoord1bvOES" tex-coord-1bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glTexCoord2bOES" tex-coord-2b-oes) :void
  (s byte)
  (tee byte))

(defglextfun ("glTexCoord2bvOES" tex-coord-2bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glTexCoord3bOES" tex-coord-3b-oes) :void
  (s byte)
  (tee byte)
  (r byte))

(defglextfun ("glTexCoord3bvOES" tex-coord-3bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glTexCoord4bOES" tex-coord-4b-oes) :void
  (s byte)
  (tee byte)
  (r byte)
  (q byte))

(defglextfun ("glTexCoord4bvOES" tex-coord-4bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glVertex2bOES" vertex-2b-oes) :void
  (x byte)
  (y byte))

(defglextfun ("glVertex2bvOES" vertex-2bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glVertex3bOES" vertex-3b-oes) :void
  (x byte)
  (y byte)
  (z byte))

(defglextfun ("glVertex3bvOES" vertex-3bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glVertex4bOES" vertex-4b-oes) :void
  (x byte)
  (y byte)
  (z byte)
  (w byte))

(defglextfun ("glVertex4bvOES" vertex-4bv-oes) :void
  (coords (:pointer byte)))

(defglextfun ("glAlphaFuncxOES" alpha-func-x-oes) :void
  (func alpha-function)
  (ref fixed))

(defglextfun ("glClearColorxOES" clear-color-x-oes) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglextfun ("glClearDepthxOES" clear-depth-x-oes) :void
  (depth fixed))

(defglextfun ("glClipPlanexOES" clip-plane-x-oes) :void
  (plane clip-plane-name)
  (equation (:pointer fixed)))

(defglextfun ("glColor4xOES" color-4x-oes) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglextfun ("glDepthRangexOES" depth-range-x-oes) :void
  (n fixed)
  (f fixed))

(defglextfun ("glFogxOES" fog-x-oes) :void
  (pname fog-pname)
  (param fixed))

(defglextfun ("glFogxvOES" fog-xv-oes) :void
  (pname fog-pname)
  (param (:pointer fixed)))

(defglextfun ("glFrustumxOES" frustum-x-oes) :void
  (l fixed)
  (r fixed)
  (b fixed)
  (tee fixed)
  (n fixed)
  (f fixed))

(defglextfun ("glGetClipPlanexOES" get-clip-plane-x-oes) :void
  (plane clip-plane-name)
  (equation (:pointer fixed)))

(defglextfun ("glGetFixedvOES" get-fixed-v-oes) :void
  (pname get-pname)
  (params (:pointer fixed)))

(defglextfun ("glGetTexEnvxvOES" get-tex-env-xv-oes) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer fixed)))

(defglextfun ("glGetTexParameterxvOES" get-tex-parameter-xv-oes) :void
  (target texture-target)
  (pname get-texture-parameter)
  (params (:pointer fixed)))

(defglextfun ("glLightModelxOES" light-model-x-oes) :void
  (pname light-model-parameter)
  (param fixed))

(defglextfun ("glLightModelxvOES" light-model-xv-oes) :void
  (pname light-model-parameter)
  (param (:pointer fixed)))

(defglextfun ("glLightxOES" light-x-oes) :void
  (light light-name)
  (pname light-parameter)
  (param fixed))

(defglextfun ("glLightxvOES" light-xv-oes) :void
  (light light-name)
  (pname light-parameter)
  (params (:pointer fixed)))

(defglextfun ("glLineWidthxOES" line-width-x-oes) :void
  (width fixed))

(defglextfun ("glLoadMatrixxOES" load-matrix-x-oes) :void
  (m (:pointer fixed)))

(defglextfun ("glMaterialxOES" material-x-oes) :void
  (face material-face)
  (pname material-parameter)
  (param fixed))

(defglextfun ("glMaterialxvOES" material-xv-oes) :void
  (face material-face)
  (pname material-parameter)
  (param (:pointer fixed)))

(defglextfun ("glMultMatrixxOES" mult-matrix-x-oes) :void
  (m (:pointer fixed)))

(defglextfun ("glMultiTexCoord4xOES" multi-tex-coord-4x-oes) :void
  (texture texture-unit)
  (s fixed)
  (tee fixed)
  (r fixed)
  (q fixed))

(defglextfun ("glNormal3xOES" normal-3x-oes) :void
  (nx fixed)
  (ny fixed)
  (nz fixed))

(defglextfun ("glOrthoxOES" ortho-x-oes) :void
  (l fixed)
  (r fixed)
  (b fixed)
  (tee fixed)
  (n fixed)
  (f fixed))

(defglextfun ("glPointParameterxvOES" point-parameter-xv-oes) :void
  (pname point-parameter-name-arb)
  (params (:pointer fixed)))

(defglextfun ("glPointSizexOES" point-size-x-oes) :void
  (size fixed))

(defglextfun ("glPolygonOffsetxOES" polygon-offset-x-oes) :void
  (factor fixed)
  (units fixed))

(defglextfun ("glRotatexOES" rotate-x-oes) :void
  (angle fixed)
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glScalexOES" scale-x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glTexEnvxOES" tex-env-x-oes) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (param fixed))

(defglextfun ("glTexEnvxvOES" tex-env-xv-oes) :void
  (target texture-env-target)
  (pname texture-env-parameter)
  (params (:pointer fixed)))

(defglextfun ("glTexParameterxOES" tex-parameter-x-oes) :void
  (target texture-target)
  (pname get-texture-parameter)
  (param fixed))

(defglextfun ("glTexParameterxvOES" tex-parameter-xv-oes) :void
  (target texture-target)
  (pname get-texture-parameter)
  (params (:pointer fixed)))

(defglextfun ("glTranslatexOES" translate-x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glGetLightxvOES" get-light-xv-oes) :void
  (light light-name)
  (pname light-parameter)
  (params (:pointer fixed)))

(defglextfun ("glGetMaterialxvOES" get-material-xv-oes) :void
  (face material-face)
  (pname material-parameter)
  (params (:pointer fixed)))

(defglextfun ("glPointParameterxOES" point-parameter-x-oes) :void
  (pname point-parameter-name-arb)
  (param fixed))

(defglextfun ("glSampleCoveragexOES" sample-coverage-x-oes) :void
  (value clampx)
  (invert boolean))

(defglextfun ("glAccumxOES" accum-x-oes) :void
  (op enum)
  (value fixed))

(defglextfun ("glBitmapxOES" bitmap-x-oes) :void
  (width sizei)
  (height sizei)
  (xorig fixed)
  (yorig fixed)
  (xmove fixed)
  (ymove fixed)
  (bitmap (:pointer ubyte)))

(defglextfun ("glBlendColorxOES" blend-color-x-oes) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglextfun ("glClearAccumxOES" clear-accum-x-oes) :void
  (red fixed)
  (green fixed)
  (blue fixed)
  (alpha fixed))

(defglextfun ("glColor3xOES" color-3x-oes) :void
  (red fixed)
  (green fixed)
  (blue fixed))

(defglextfun ("glColor3xvOES" color-3xv-oes) :void
  (components (:pointer fixed)))

(defglextfun ("glColor4xvOES" color-4xv-oes) :void
  (components (:pointer fixed)))

(defglextfun ("glConvolutionParameterxOES" convolution-parameter-x-oes) :void
  (target convolution-target-ext)
  (pname convolution-parameter-ext)
  (param fixed))

(defglextfun ("glConvolutionParameterxvOES" convolution-parameter-xv-oes) :void
  (target convolution-target-ext)
  (pname convolution-parameter-ext)
  (params (:pointer fixed)))

(defglextfun ("glEvalCoord1xOES" eval-coord-1x-oes) :void
  (u fixed))

(defglextfun ("glEvalCoord1xvOES" eval-coord-1xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glEvalCoord2xOES" eval-coord-2x-oes) :void
  (u fixed)
  (v fixed))

(defglextfun ("glEvalCoord2xvOES" eval-coord-2xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glFeedbackBufferxOES" feedback-buffer-x-oes) :void
  (n sizei)
  (type enum)
  (buffer (:pointer fixed)))

(defglextfun ("glGetConvolutionParameterxvOES" get-convolution-parameter-xv-oes) :void
  (target enum)
  (pname enum)
  (params (:pointer fixed)))

(defglextfun ("glGetHistogramParameterxvOES" get-histogram-parameter-xv-oes) :void
  (target histogram-target-ext)
  (pname get-histogram-parameter-pname-ext)
  (params (:pointer fixed)))

(defglextfun ("glGetLightxOES" get-light-x-oes) :void
  (light light-name)
  (pname light-parameter)
  (params (:pointer fixed)))

(defglextfun ("glGetMapxvOES" get-map-xv-oes) :void
  (target map-target)
  (query get-map-query)
  (v (:pointer fixed)))

(defglextfun ("glGetMaterialxOES" get-material-x-oes) :void
  (face material-face)
  (pname material-parameter)
  (param fixed))

(defglextfun ("glGetPixelMapxv" get-pixel-map-xv) :void
  (map pixel-map)
  (size int)
  (values (:pointer fixed)))

(defglextfun ("glGetTexGenxvOES" get-tex-gen-xv-oes) :void
  (coord texture-coord-name)
  (pname texture-gen-parameter)
  (params (:pointer fixed)))

(defglextfun ("glGetTexLevelParameterxvOES" get-tex-level-parameter-xv-oes) :void
  (target texture-target)
  (level int)
  (pname get-texture-parameter)
  (params (:pointer fixed)))

(defglextfun ("glIndexxOES" index-x-oes) :void
  (component fixed))

(defglextfun ("glIndexxvOES" index-xv-oes) :void
  (component (:pointer fixed)))

(defglextfun ("glLoadTransposeMatrixxOES" load-transpose-matrix-x-oes) :void
  (m (:pointer fixed)))

(defglextfun ("glMap1xOES" map-1x-oes) :void
  (target map-target)
  (u1 fixed)
  (u2 fixed)
  (stride int)
  (order int)
  (points fixed))

(defglextfun ("glMap2xOES" map-2x-oes) :void
  (target map-target)
  (u1 fixed)
  (u2 fixed)
  (ustride int)
  (uorder int)
  (v1 fixed)
  (v2 fixed)
  (vstride int)
  (vorder int)
  (points fixed))

(defglextfun ("glMapGrid1xOES" map-grid-1x-oes) :void
  (n int)
  (u1 fixed)
  (u2 fixed))

(defglextfun ("glMapGrid2xOES" map-grid-2x-oes) :void
  (n int)
  (u1 fixed)
  (u2 fixed)
  (v1 fixed)
  (v2 fixed))

(defglextfun ("glMultTransposeMatrixxOES" mult-transpose-matrix-x-oes) :void
  (m (:pointer fixed)))

(defglextfun ("glMultiTexCoord1xOES" multi-tex-coord-1x-oes) :void
  (texture texture-unit)
  (s fixed))

(defglextfun ("glMultiTexCoord1xvOES" multi-tex-coord-1xv-oes) :void
  (texture texture-unit)
  (coords (:pointer fixed)))

(defglextfun ("glMultiTexCoord2xOES" multi-tex-coord-2x-oes) :void
  (texture texture-unit)
  (s fixed)
  (tee fixed))

(defglextfun ("glMultiTexCoord2xvOES" multi-tex-coord-2xv-oes) :void
  (texture texture-unit)
  (coords (:pointer fixed)))

(defglextfun ("glMultiTexCoord3xOES" multi-tex-coord-3x-oes) :void
  (texture texture-unit)
  (s fixed)
  (tee fixed)
  (r fixed))

(defglextfun ("glMultiTexCoord3xvOES" multi-tex-coord-3xv-oes) :void
  (texture texture-unit)
  (coords (:pointer fixed)))

(defglextfun ("glMultiTexCoord4xvOES" multi-tex-coord-4xv-oes) :void
  (texture texture-unit)
  (coords (:pointer fixed)))

(defglextfun ("glNormal3xvOES" normal-3xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glPassThroughxOES" pass-through-x-oes) :void
  (token fixed))

(defglextfun ("glPixelMapx" pixel-map-x) :void
  (map pixel-map)
  (size int)
  (values (:pointer fixed)))

(defglextfun ("glPixelStorex" pixel-store-x) :void
  (pname pixel-store-parameter)
  (param fixed))

(defglextfun ("glPixelTransferxOES" pixel-transfer-x-oes) :void
  (pname pixel-transfer-parameter)
  (param fixed))

(defglextfun ("glPixelZoomxOES" pixel-zoom-x-oes) :void
  (xfactor fixed)
  (yfactor fixed))

(defglextfun ("glPrioritizeTexturesxOES" prioritize-textures-x-oes) :void
  (n sizei)
  (textures (:pointer uint))
  (priorities (:pointer fixed)))

(defglextfun ("glRasterPos2xOES" raster-pos-2x-oes) :void
  (x fixed)
  (y fixed))

(defglextfun ("glRasterPos2xvOES" raster-pos-2xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glRasterPos3xOES" raster-pos-3x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glRasterPos3xvOES" raster-pos-3xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glRasterPos4xOES" raster-pos-4x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed)
  (w fixed))

(defglextfun ("glRasterPos4xvOES" raster-pos-4xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glRectxOES" rect-x-oes) :void
  (x1 fixed)
  (y1 fixed)
  (x2 fixed)
  (y2 fixed))

(defglextfun ("glRectxvOES" rect-xv-oes) :void
  (v1 (:pointer fixed))
  (v2 (:pointer fixed)))

(defglextfun ("glTexCoord1xOES" tex-coord-1x-oes) :void
  (s fixed))

(defglextfun ("glTexCoord1xvOES" tex-coord-1xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glTexCoord2xOES" tex-coord-2x-oes) :void
  (s fixed)
  (tee fixed))

(defglextfun ("glTexCoord2xvOES" tex-coord-2xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glTexCoord3xOES" tex-coord-3x-oes) :void
  (s fixed)
  (tee fixed)
  (r fixed))

(defglextfun ("glTexCoord3xvOES" tex-coord-3xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glTexCoord4xOES" tex-coord-4x-oes) :void
  (s fixed)
  (tee fixed)
  (r fixed)
  (q fixed))

(defglextfun ("glTexCoord4xvOES" tex-coord-4xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glTexGenxOES" tex-gen-x-oes) :void
  (coord texture-coord-name)
  (pname texture-gen-parameter)
  (param fixed))

(defglextfun ("glTexGenxvOES" tex-gen-xv-oes) :void
  (coord texture-coord-name)
  (pname texture-gen-parameter)
  (params (:pointer fixed)))

(defglextfun ("glVertex2xOES" vertex-2x-oes) :void
  (x fixed))

(defglextfun ("glVertex2xvOES" vertex-2xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glVertex3xOES" vertex-3x-oes) :void
  (x fixed)
  (y fixed))

(defglextfun ("glVertex3xvOES" vertex-3xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glVertex4xOES" vertex-4x-oes) :void
  (x fixed)
  (y fixed)
  (z fixed))

(defglextfun ("glVertex4xvOES" vertex-4xv-oes) :void
  (coords (:pointer fixed)))

(defglextfun ("glQueryMatrixxOES" query-matrix-x-oes) bitfield
  (mantissa (:pointer fixed))
  (exponent (:pointer int)))

(defglextfun ("glClearDepthfOES" clear-depth-f-oes) :void
  (depth clampf))

(defglextfun ("glClipPlanefOES" clip-plane-f-oes) :void
  (plane clip-plane-name)
  (equation (:pointer float)))

(defglextfun ("glDepthRangefOES" depth-range-f-oes) :void
  (n clampf)
  (f clampf))

(defglextfun ("glFrustumfOES" frustum-f-oes) :void
  (l float)
  (r float)
  (b float)
  (tee float)
  (n float)
  (f float))

(defglextfun ("glGetClipPlanefOES" get-clip-plane-f-oes) :void
  (plane clip-plane-name)
  (equation (:pointer float)))

(defglextfun ("glOrthofOES" ortho-f-oes) :void
  (l float)
  (r float)
  (b float)
  (tee float)
  (n float)
  (f float))

