;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2024-08-16T20:46:56Z
;;; from gl.xml @ git sha 4f845dc97972c72cad684cc22c7bf96e6d5319a6, 2024-08-15T14:04:09Z

(defglextfun ("glCopyTextureLevelsAPPLE" copy-texture-levels-apple 0) :void
  (destinationTexture uint)
  (sourceTexture uint)
  (sourceBaseLevel int)
  (sourceLevelCount sizei))

(defglextfun ("glRenderbufferStorageMultisampleAPPLE" renderbuffer-storage-multisample-apple 1) :void
  (target enum)
  (samples sizei)
  (internalformat enum)
  (width sizei)
  (height sizei))

(defglextfun ("glResolveMultisampleFramebufferAPPLE" resolve-multisample-framebuffer-apple 2) :void)

(defglextfun ("glFenceSyncAPPLE" fence-sync-apple 3) sync
  (condition enum)
  (flags SyncBehaviorFlags))

(defglextfun ("glIsSyncAPPLE" is-sync-apple 4) boolean
  (sync sync))

(defglextfun ("glDeleteSyncAPPLE" delete-sync-apple 5) :void
  (sync sync))

(defglextfun ("glClientWaitSyncAPPLE" client-wait-sync-apple 6) enum
  (sync sync)
  (flags SyncObjectMask)
  (timeout uint64))

(defglextfun ("glWaitSyncAPPLE" wait-sync-apple 7) :void
  (sync sync)
  (flags SyncBehaviorFlags)
  (timeout uint64))

(defglextfun ("glGetInteger64vAPPLE" get-integer-64-v-apple 8) :void
  (pname enum)
  (params (:pointer int64)))

(defglextfun ("glGetSyncivAPPLE" get-sync-iv-apple 9) :void
  (sync sync)
  (pname enum)
  (count sizei)
  (length (:pointer sizei))
  (values (:pointer int)))

(defglextfun ("glDiscardFramebufferEXT" discard-framebuffer-ext 10) :void
  (target enum)
  (numAttachments sizei)
  (attachments (:pointer enum)))

(defglextfun ("glMapBufferRangeEXT" map-buffer-range-ext 11) (:pointer :void)
  (target enum)
  (offset intptr)
  (length sizeiptr)
  (access MapBufferAccessMask))

(defglextfun ("glFlushMappedBufferRangeEXT" flush-mapped-buffer-range-ext 12) :void
  (target enum)
  (offset intptr)
  (length sizeiptr))

(defglextfun ("glFramebufferTexture2DMultisampleEXT" framebuffer-texture-2d-multisample-ext 13) :void
  (target enum)
  (attachment enum)
  (textarget enum)
  (texture uint)
  (level int)
  (samples sizei))

(defglextfun ("glGetGraphicsResetStatusEXT" get-graphics-reset-status-ext 14) enum)

(defglextfun ("glReadnPixelsEXT" readn-pixels-ext 15) :void
  (x int)
  (y int)
  (width sizei)
  (height sizei)
  (format enum)
  (type enum)
  (bufSize sizei)
  (data (:pointer :void)))

(defglextfun ("glGetnUniformfvEXT" getn-uniformfv-ext 16) :void
  (program uint)
  (location int)
  (bufSize sizei)
  (params (:pointer float)))

(defglextfun ("glGetnUniformivEXT" getn-uniformiv-ext 17) :void
  (program uint)
  (location int)
  (bufSize sizei)
  (params (:pointer int)))

(defglextfun ("glRenderbufferStorageMultisampleIMG" renderbuffer-storage-multisample-img 18) :void
  (target enum)
  (samples sizei)
  (internalformat enum)
  (width sizei)
  (height sizei))

(defglextfun ("glFramebufferTexture2DMultisampleIMG" framebuffer-texture-2d-multisample-img 19) :void
  (target enum)
  (attachment enum)
  (textarget enum)
  (texture uint)
  (level int)
  (samples sizei))

(defglextfun ("glEGLImageTargetTexture2DOES" egl-image-target-texture-2d-oes 20) :void
  (target enum)
  (image egl-image-oes))

(defglextfun ("glEGLImageTargetRenderbufferStorageOES" egl-image-target-renderbuffer-storage-oes 21) :void
  (target enum)
  (image egl-image-oes))

(defglextfun ("glMapBufferOES" map-buffer-oes 22) (:pointer :void)
  (target enum)
  (access enum))

(defglextfun ("glUnmapBufferOES" unmap-buffer-oes 23) boolean
  (target enum))

(defglextfun ("glGetBufferPointervOES" get-buffer-pointer-v-oes 24) :void
  (target enum)
  (pname enum)
  (params (:pointer (:pointer :void))))

(defglextfun ("glBindVertexArrayOES" bind-vertex-array-oes 25) :void
  (array uint))

(defglextfun ("glDeleteVertexArraysOES" delete-vertex-arrays-oes 26) :void
  (n sizei)
  (arrays (:pointer uint)))

(defglextfun ("glGenVertexArraysOES" gen-vertex-arrays-oes 27) :void
  (n sizei)
  (arrays (:pointer uint)))

(defglextfun ("glIsVertexArrayOES" is-vertex-array-oes 28) boolean
  (array uint))

(defglextfun ("glGetDriverControlsQCOM" get-driver-controls-qcom 29) :void
  (num (:pointer int))
  (size sizei)
  (driverControls (:pointer uint)))

(defglextfun ("glGetDriverControlStringQCOM" get-driver-control-string-qcom 30) :void
  (driverControl uint)
  (bufSize sizei)
  (length (:pointer sizei))
  (driverControlString (:pointer char)))

(defglextfun ("glEnableDriverControlQCOM" enable-driver-control-qcom 31) :void
  (driverControl uint))

(defglextfun ("glDisableDriverControlQCOM" disable-driver-control-qcom 32) :void
  (driverControl uint))

(defglextfun ("glExtGetTexturesQCOM" ext-get-textures-qcom 33) :void
  (textures (:pointer uint))
  (maxTextures int)
  (numTextures (:pointer int)))

(defglextfun ("glExtGetBuffersQCOM" ext-get-buffers-qcom 34) :void
  (buffers (:pointer uint))
  (maxBuffers int)
  (numBuffers (:pointer int)))

(defglextfun ("glExtGetRenderbuffersQCOM" ext-get-renderbuffers-qcom 35) :void
  (renderbuffers (:pointer uint))
  (maxRenderbuffers int)
  (numRenderbuffers (:pointer int)))

(defglextfun ("glExtGetFramebuffersQCOM" ext-get-framebuffers-qcom 36) :void
  (framebuffers (:pointer uint))
  (maxFramebuffers int)
  (numFramebuffers (:pointer int)))

(defglextfun ("glExtGetTexLevelParameterivQCOM" ext-get-tex-level-parameter-iv-qcom 37) :void
  (texture uint)
  (face enum)
  (level int)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glExtTexObjectStateOverrideiQCOM" ext-tex-object-state-override-i-qcom 38) :void
  (target enum)
  (pname enum)
  (param int))

(defglextfun ("glExtGetTexSubImageQCOM" ext-get-tex-sub-image-qcom 39) :void
  (target enum)
  (level int)
  (xoffset int)
  (yoffset int)
  (zoffset int)
  (width sizei)
  (height sizei)
  (depth sizei)
  (format enum)
  (type enum)
  (texels (:pointer :void)))

(defglextfun ("glExtGetBufferPointervQCOM" ext-get-buffer-pointer-v-qcom 40) :void
  (target enum)
  (params (:pointer (:pointer :void))))

(defglextfun ("glExtGetShadersQCOM" ext-get-shaders-qcom 41) :void
  (shaders (:pointer uint))
  (maxShaders int)
  (numShaders (:pointer int)))

(defglextfun ("glExtGetProgramsQCOM" ext-get-programs-qcom 42) :void
  (programs (:pointer uint))
  (maxPrograms int)
  (numPrograms (:pointer int)))

(defglextfun ("glExtIsProgramBinaryQCOM" ext-is-program-binary-qcom 43) boolean
  (program uint))

(defglextfun ("glExtGetProgramBinarySourceQCOM" ext-get-program-binary-source-qcom 44) :void
  (program uint)
  (shadertype enum)
  (source (:pointer char))
  (length (:pointer int)))

(defglextfun ("glStartTilingQCOM" start-tiling-qcom 45) :void
  (x uint)
  (y uint)
  (width uint)
  (height uint)
  (preserveMask BufferBitQCOM))

(defglextfun ("glEndTilingQCOM" end-tiling-qcom 46) :void
  (preserveMask BufferBitQCOM))

