;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2023-12-17T01:10:57Z
;;; from gl.xml @ git sha bb9a7d9bd49408d709e7481e34b689db3b13317c, 2023-12-06T16:19:18Z

(defparameter *glext-version* 20231206)
(defparameter *glext-last-updated* "2023-12-06T16:19:18Z")

(defglextfun ("glDepthRangef" depth-range-f) :void
  (n float)
  (f float))

(defglextfun ("glClearDepthf" clear-depth-f) :void
  (d float))

