;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2020-10-13T02:36:23Z
;;; from gl.xml @ git sha d580a9cd9c22452cb2ec3a7caf4a506fe0557b8d, 2020-10-13T02:28:36Z

(defglfun ("glTexImage2D" tex-image-2d) :void
  (target texture-target)
  (level int)
  (internalformat int)
  (width sizei)
  (height sizei)
  (border int)
  (format pixel-format)
  (type pixel-type)
  (pixels offset-or-pointer))

(defglfun ("glReadPixels" read-pixels) :void
  (x int)
  (y int)
  (width sizei)
  (height sizei)
  (format pixel-format)
  (type pixel-type)
  (pixels offset-or-pointer))

(defglfun ("glDrawElements" draw-elements) :void
  (mode primitive-type)
  (count sizei)
  (type draw-elements-type)
  (indices offset-or-pointer))

(defglfun ("glCopyTexImage2D" copy-tex-image-2d) :void
  (target texture-target)
  (level int)
  (internalformat internal-format)
  (x int)
  (y int)
  (width sizei)
  (height sizei)
  (border int))

(defglfun ("glCopyTexSubImage2D" copy-tex-sub-image-2d) :void
  (target texture-target)
  (level int)
  (xoffset int)
  (yoffset int)
  (x int)
  (y int)
  (width sizei)
  (height sizei))

(defglfun ("glDeleteTextures" delete-textures) :void
  (n sizei)
  (textures (:pointer uint)))

(defglfun ("glIsTexture" is-texture) boolean
  (texture uint))

(defglextfun ("glCompressedTexImage2D" compressed-tex-image-2d) :void
  (target texture-target)
  (level int)
  (internalformat internal-format)
  (width sizei)
  (height sizei)
  (border int)
  (imageSize sizei)
  (data offset-or-pointer))

(defglextfun ("glDeleteBuffers" delete-buffers) :void
  (n sizei)
  (buffers (:pointer uint)))

(defglextfun ("glIsBuffer" is-buffer) boolean
  (buffer uint))

(defglextfun ("glBlendEquationEXT" blend-equation-ext) :void
  (mode blend-equation-mode-ext))

(defglextfun ("glRenderbufferStorageMultisampleEXT" renderbuffer-storage-multisample-ext) :void
  (target renderbuffer-target)
  (samples sizei)
  (internalformat internal-format)
  (width sizei)
  (height sizei))

(defglextfun ("glMultiDrawArraysEXT" multi-draw-arrays-ext) :void
  (mode primitive-type)
  (first (:pointer int))
  (count (:pointer sizei))
  (primcount sizei))

(defglextfun ("glMultiDrawElementsEXT" multi-draw-elements-ext) :void
  (mode primitive-type)
  (count (:pointer sizei))
  (type draw-elements-type)
  (indices (:pointer (:pointer :void)))
  (primcount sizei))

(defglextfun ("glDeleteFencesNV" delete-fences-nv) :void
  (n sizei)
  (fences (:pointer uint)))

(defglextfun ("glGenFencesNV" gen-fences-nv) :void
  (n sizei)
  (fences (:pointer uint)))

(defglextfun ("glIsFenceNV" is-fence-nv) boolean
  (fence uint))

(defglextfun ("glTestFenceNV" test-fence-nv) boolean
  (fence uint))

(defglextfun ("glGetFenceivNV" get-fence-iv-nv) :void
  (fence uint)
  (pname fence-parameter-name-nv)
  (params (:pointer int)))

(defglextfun ("glFinishFenceNV" finish-fence-nv) :void
  (fence uint))

(defglextfun ("glSetFenceNV" set-fence-nv) :void
  (fence uint)
  (condition fence-condition-nv))

