;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2020-10-03T16:20:47Z
;;; from gl.xml @ git sha 9274192362a0ac6912fd27b0c8ff0559fc658e21, 2020-09-29T11:45:14Z

(defparameter *glext-version* 20200929)
(defparameter *glext-last-updated* "2020-09-29T11:45:14Z")

(defglextfun ("glDepthRangef" depth-range-f) :void
  (n float)
  (f float))

(defglextfun ("glClearDepthf" clear-depth-f) :void
  (d float))

