;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright (c) 2013 The Khronos Group Inc.
;;;
;;; Permission is hereby granted, free of charge, to any person obtaining a
;;; copy of this software and/or associated documentation files (the
;;; "Materials"), to deal in the Materials without restriction, including
;;; without limitation the rights to use, copy, modify, merge, publish,
;;; distribute, sublicense, and/or sell copies of the Materials, and to
;;; permit persons to whom the Materials are furnished to do so, subject to
;;; the following conditions:
;;;
;;; The above copyright notice and this permission notice shall be included
;;; in all copies or substantial portions of the Materials.
;;;
;;; THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
;;; IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
;;; CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
;;; TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
;;; MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
;;;
;;; ------------------------------------------------------------------------

(in-package #:cl-opengl-bindings)

;;; generated 2013-08-25T10:55:36Z
;;; from gl.xml @ svn rev 22836, 2013-08-23T22:13:48.757953Z

(defglfun ("glCullFace" cull-face) :void
  (mode enum))

(defglfun ("glFrontFace" front-face) :void
  (mode enum))

(defglfun ("glHint" hint) :void
  (target enum)
  (mode enum))

(defglfun ("glLineWidth" line-width) :void
  (width float))

(defglfun ("glScissor" scissor) :void
  (x int)
  (y int)
  (width sizei)
  (height sizei))

(defglfun ("glTexParameterf" tex-parameter-f) :void
  (target enum)
  (pname enum)
  (param float))

(defglfun ("glTexParameterfv" tex-parameter-fv) :void
  (target enum)
  (pname enum)
  (params (:pointer float)))

(defglfun ("glTexParameteri" tex-parameter-i) :void
  (target enum)
  (pname enum)
  (param int))

(defglfun ("glTexParameteriv" tex-parameter-iv) :void
  (target enum)
  (pname enum)
  (params (:pointer int)))

(defglfun ("glTexImage2D" tex-image-2d) :void
  (target enum)
  (level int)
  (internalformat int)
  (width sizei)
  (height sizei)
  (border int)
  (format enum)
  (type enum)
  (pixels offset-or-pointer))

(defglfun ("glClear" clear) :void
  (mask ClearBufferMask))

(defglfun ("glClearColor" clear-color) :void
  (red float)
  (green float)
  (blue float)
  (alpha float))

(defglfun ("glClearStencil" clear-stencil) :void
  (s int))

(defglfun ("glStencilMask" stencil-mask) :void
  (mask uint))

(defglfun ("glColorMask" color-mask) :void
  (red boolean)
  (green boolean)
  (blue boolean)
  (alpha boolean))

(defglfun ("glDepthMask" depth-mask) :void
  (flag boolean))

(defglfun ("glDisable" disable) :void
  (cap enum))

(defglfun ("glEnable" enable) :void
  (cap enum))

(defglfun ("glFinish" finish) :void)

(defglfun ("glFlush" flush) :void)

(defglfun ("glBlendFunc" blend-func) :void
  (sfactor enum)
  (dfactor enum))

(defglfun ("glStencilFunc" stencil-func) :void
  (func enum)
  (ref int)
  (mask uint))

(defglfun ("glStencilOp" stencil-op) :void
  (fail enum)
  (zfail enum)
  (zpass enum))

(defglfun ("glDepthFunc" depth-func) :void
  (func enum))

(defglfun ("glPixelStorei" pixel-store-i) :void
  (pname enum)
  (param int))

(defglfun ("glReadPixels" read-pixels) :void
  (x int)
  (y int)
  (width sizei)
  (height sizei)
  (format enum)
  (type enum)
  (pixels offset-or-pointer))

(defglfun ("glGetBooleanv" get-boolean-v) :void
  (pname enum)
  (params (:pointer boolean)))

(defglfun ("glGetError" get-error) enum)

(defglfun ("glGetFloatv" get-float-v) :void
  (pname enum)
  (params (:pointer float)))

(defglfun ("glGetIntegerv" get-integer-v) :void
  (pname enum)
  (params (:pointer int)))

(defglfun ("glGetString" get-string) string
  (name enum))

(defglfun ("glGetTexParameterfv" get-tex-parameter-fv) :void
  (target enum)
  (pname enum)
  (params (:pointer float)))

(defglfun ("glGetTexParameteriv" get-tex-parameter-iv) :void
  (target enum)
  (pname enum)
  (params (:pointer int)))

(defglfun ("glIsEnabled" is-enabled) boolean
  (cap enum))

(defglfun ("glViewport" viewport) :void
  (x int)
  (y int)
  (width sizei)
  (height sizei))

(defglfun ("glDrawArrays" draw-arrays) :void
  (mode enum)
  (first int)
  (count sizei))

(defglfun ("glDrawElements" draw-elements) :void
  (mode enum)
  (count sizei)
  (type enum)
  (indices offset-or-pointer))

(defglfun ("glPolygonOffset" polygon-offset) :void
  (factor float)
  (units float))

(defglfun ("glCopyTexImage2D" copy-tex-image-2d) :void
  (target enum)
  (level int)
  (internalformat enum)
  (x int)
  (y int)
  (width sizei)
  (height sizei)
  (border int))

(defglfun ("glCopyTexSubImage2D" copy-tex-sub-image-2d) :void
  (target enum)
  (level int)
  (xoffset int)
  (yoffset int)
  (x int)
  (y int)
  (width sizei)
  (height sizei))

(defglfun ("glTexSubImage2D" tex-sub-image-2d) :void
  (target enum)
  (level int)
  (xoffset int)
  (yoffset int)
  (width sizei)
  (height sizei)
  (format enum)
  (type enum)
  (pixels offset-or-pointer))

(defglfun ("glBindTexture" bind-texture) :void
  (target enum)
  (texture uint))

(defglfun ("glDeleteTextures" delete-textures) :void
  (n sizei)
  (textures (:pointer uint)))

(defglfun ("glGenTextures" gen-textures) :void
  (n sizei)
  (textures (:pointer uint)))

(defglfun ("glIsTexture" is-texture) boolean
  (texture uint))

(defglextfun ("glActiveTexture" active-texture) :void
  (texture enum))

(defglextfun ("glSampleCoverage" sample-coverage) :void
  (value float)
  (invert boolean))

(defglextfun ("glCompressedTexImage2D" compressed-tex-image-2d) :void
  (target enum)
  (level int)
  (internalformat enum)
  (width sizei)
  (height sizei)
  (border int)
  (imageSize sizei)
  (data offset-or-pointer))

(defglextfun ("glCompressedTexSubImage2D" compressed-tex-sub-image-2d) :void
  (target enum)
  (level int)
  (xoffset int)
  (yoffset int)
  (width sizei)
  (height sizei)
  (format enum)
  (imageSize sizei)
  (data offset-or-pointer))

(defglextfun ("glBindBuffer" bind-buffer) :void
  (target enum)
  (buffer uint))

(defglextfun ("glDeleteBuffers" delete-buffers) :void
  (n sizei)
  (buffers (:pointer uint)))

(defglextfun ("glGenBuffers" gen-buffers) :void
  (n sizei)
  (buffers (:pointer uint)))

(defglextfun ("glIsBuffer" is-buffer) boolean
  (buffer uint))

(defglextfun ("glBufferData" buffer-data) :void
  (target enum)
  (size sizeiptr)
  (data (:pointer void))
  (usage enum))

(defglextfun ("glBufferSubData" buffer-sub-data) :void
  (target enum)
  (offset intptr)
  (size sizeiptr)
  (data (:pointer void)))

(defglextfun ("glGetBufferParameteriv" get-buffer-parameter-iv) :void
  (target enum)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glBlendEquationEXT" blend-equation-ext) :void
  (mode enum))

(defglextfun ("glTextureStorage1DEXT" texture-storage-1d-ext) :void
  (texture uint)
  (target enum)
  (levels sizei)
  (internalformat enum)
  (width sizei))

(defglextfun ("glTextureStorage2DEXT" texture-storage-2d-ext) :void
  (texture uint)
  (target enum)
  (levels sizei)
  (internalformat enum)
  (width sizei)
  (height sizei))

(defglextfun ("glTextureStorage3DEXT" texture-storage-3d-ext) :void
  (texture uint)
  (target enum)
  (levels sizei)
  (internalformat enum)
  (width sizei)
  (height sizei)
  (depth sizei))

(defglextfun ("glRenderbufferStorageMultisampleEXT" renderbuffer-storage-multisample-ext) :void
  (target enum)
  (samples sizei)
  (internalformat enum)
  (width sizei)
  (height sizei))

(defglextfun ("glMultiDrawArraysEXT" multi-draw-arrays-ext) :void
  (mode enum)
  (first (:pointer int))
  (count (:pointer sizei))
  (primcount sizei))

(defglextfun ("glMultiDrawElementsEXT" multi-draw-elements-ext) :void
  (mode enum)
  (count (:pointer sizei))
  (type enum)
  (indices (:pointer (:pointer void)))
  (primcount sizei))

(defglextfun ("glDeleteFencesNV" delete-fences-nv) :void
  (n sizei)
  (fences (:pointer uint)))

(defglextfun ("glGenFencesNV" gen-fences-nv) :void
  (n sizei)
  (fences (:pointer uint)))

(defglextfun ("glIsFenceNV" is-fence-nv) boolean
  (fence uint))

(defglextfun ("glTestFenceNV" test-fence-nv) boolean
  (fence uint))

(defglextfun ("glGetFenceivNV" get-fence-iv-nv) :void
  (fence uint)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glFinishFenceNV" finish-fence-nv) :void
  (fence uint))

(defglextfun ("glSetFenceNV" set-fence-nv) :void
  (fence uint)
  (condition enum))

