;;; this file is automatically generated, do not edit
;;; generated from files with the following copyright:
;;;
;;; Copyright 2013-2020 The Khronos Group Inc.
;;; SPDX-License-Identifier: Apache-2.0

(in-package #:cl-opengl-bindings)

;;; generated 2024-08-16T20:46:56Z
;;; from gl.xml @ git sha 4f845dc97972c72cad684cc22c7bf96e6d5319a6, 2024-08-15T14:04:09Z

(defglextfun ("glDrawRangeElements" draw-range-elements 1373) :void
  (mode enum)
  (start uint)
  (end uint)
  (count sizei)
  (type enum)
  (indices offset-or-pointer))

(defglextfun ("glBlendFuncSeparate" blend-func-separate 1374) :void
  (sfactorRGB enum)
  (dfactorRGB enum)
  (sfactorAlpha enum)
  (dfactorAlpha enum))

(defglextfun ("glBlendEquationSeparate" blend-equation-separate 1375) :void
  (modeRGB enum)
  (modeAlpha enum))

(defglextfun ("glStencilOpSeparate" stencil-op-separate 1376) :void
  (face enum)
  (sfail enum)
  (dpfail enum)
  (dppass enum))

(defglextfun ("glStencilFuncSeparate" stencil-func-separate 1377) :void
  (face enum)
  (func enum)
  (ref int)
  (mask uint))

(defglextfun ("glStencilMaskSeparate" stencil-mask-separate 1378) :void
  (face enum)
  (mask uint))

(defglextfun ("glCreateProgram" create-program 1379) uint)

(defglextfun ("glDisableVertexAttribArray" disable-vertex-attrib-array 1380) :void
  (index uint))

(defglextfun ("glEnableVertexAttribArray" enable-vertex-attrib-array 1381) :void
  (index uint))

(defglextfun ("glGetAttribLocation" get-attrib-location 1382) int
  (program uint)
  (name (:pointer char)))

(defglextfun ("glGetProgramiv" get-program-iv 1383) :void
  (program uint)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glGetUniformLocation" get-uniform-location 1384) int
  (program uint)
  (name (:pointer char)))

(defglextfun ("glGetVertexAttribfv" get-vertex-attrib-fv 1385) :void
  (index uint)
  (pname enum)
  (params (:pointer float)))

(defglextfun ("glGetVertexAttribiv" get-vertex-attrib-iv 1386) :void
  (index uint)
  (pname enum)
  (params (:pointer int)))

(defglextfun ("glGetVertexAttribPointerv" get-vertex-attrib-pointer-v 1387) :void
  (index uint)
  (pname enum)
  (pointer (:pointer (:pointer :void))))

(defglextfun ("glUseProgram" use-program 1388) :void
  (program uint))

(defglextfun ("glUniform1f" uniform-1f 1389) :void
  (location int)
  (v0 float))

(defglextfun ("glUniform2f" uniform-2f 1390) :void
  (location int)
  (v0 float)
  (v1 float))

(defglextfun ("glUniform3f" uniform-3f 1391) :void
  (location int)
  (v0 float)
  (v1 float)
  (v2 float))

(defglextfun ("glUniform4f" uniform-4f 1392) :void
  (location int)
  (v0 float)
  (v1 float)
  (v2 float)
  (v3 float))

(defglextfun ("glUniform1i" uniform-1i 1393) :void
  (location int)
  (v0 int))

(defglextfun ("glUniform2i" uniform-2i 1394) :void
  (location int)
  (v0 int)
  (v1 int))

(defglextfun ("glUniform3i" uniform-3i 1395) :void
  (location int)
  (v0 int)
  (v1 int)
  (v2 int))

(defglextfun ("glUniform4i" uniform-4i 1396) :void
  (location int)
  (v0 int)
  (v1 int)
  (v2 int)
  (v3 int))

(defglextfun ("glUniform1fv" uniform-1fv 1397) :void
  (location int)
  (count sizei)
  (value (:pointer float)))

(defglextfun ("glUniform2fv" uniform-2fv 1398) :void
  (location int)
  (count sizei)
  (value (:pointer float)))

(defglextfun ("glUniform3fv" uniform-3fv 1399) :void
  (location int)
  (count sizei)
  (value (:pointer float)))

(defglextfun ("glUniform4fv" uniform-4fv 1400) :void
  (location int)
  (count sizei)
  (value (:pointer float)))

(defglextfun ("glUniform1iv" uniform-1iv 1401) :void
  (location int)
  (count sizei)
  (value (:pointer int)))

(defglextfun ("glUniform2iv" uniform-2iv 1402) :void
  (location int)
  (count sizei)
  (value (:pointer int)))

(defglextfun ("glUniform3iv" uniform-3iv 1403) :void
  (location int)
  (count sizei)
  (value (:pointer int)))

(defglextfun ("glUniform4iv" uniform-4iv 1404) :void
  (location int)
  (count sizei)
  (value (:pointer int)))

(defglextfun ("glUniformMatrix2fv" uniform-matrix-2fv 1405) :void
  (location int)
  (count sizei)
  (transpose boolean)
  (value (:pointer float)))

(defglextfun ("glUniformMatrix3fv" uniform-matrix-3fv 1406) :void
  (location int)
  (count sizei)
  (transpose boolean)
  (value (:pointer float)))

(defglextfun ("glUniformMatrix4fv" uniform-matrix-4fv 1407) :void
  (location int)
  (count sizei)
  (transpose boolean)
  (value (:pointer float)))

(defglextfun ("glVertexAttrib1f" vertex-attrib-1f 1408) :void
  (index uint)
  (x float))

(defglextfun ("glVertexAttrib1fv" vertex-attrib-1fv 1409) :void
  (index uint)
  (v (:pointer float)))

(defglextfun ("glVertexAttrib2f" vertex-attrib-2f 1410) :void
  (index uint)
  (x float)
  (y float))

(defglextfun ("glVertexAttrib2fv" vertex-attrib-2fv 1411) :void
  (index uint)
  (v (:pointer float)))

(defglextfun ("glVertexAttrib3f" vertex-attrib-3f 1412) :void
  (index uint)
  (x float)
  (y float)
  (z float))

(defglextfun ("glVertexAttrib3fv" vertex-attrib-3fv 1413) :void
  (index uint)
  (v (:pointer float)))

(defglextfun ("glVertexAttrib4f" vertex-attrib-4f 1414) :void
  (index uint)
  (x float)
  (y float)
  (z float)
  (w float))

(defglextfun ("glVertexAttrib4fv" vertex-attrib-4fv 1415) :void
  (index uint)
  (v (:pointer float)))

(defglextfun ("glVertexAttribPointer" vertex-attrib-pointer 1416) :void
  (index uint)
  (size int)
  (type enum)
  (normalized boolean)
  (stride sizei)
  (pointer offset-or-pointer))

